### ISSUE TITLE
Not able to start tool examples.js

### ISSUE THREAD

**Issue by quintendewilde** [linkfy/Tools-for-Instagram#25]
I get this error. I'm running on a Raspberry PI 3+. 
I got this to run about a week ago and now I keeps hanging on this error. 

(password incorrect is shown but the password is correct though)

```
IgLoginRequiredError: GET /api/v1/accounts/current_user/?edit=true - 403 Forbidden; login_required
    at Request.handleResponseError (/home/pi/Tools-for-Instagram/node_modules/instagram-private-api/dist/core/request.js:112:24)
    at Request.send (/home/pi/Tools-for-Instagram/node_modules/instagram-private-api/dist/core/request.js:52:28)
    at async AccountRepository.currentUser (/home/pi/Tools-for-Instagram/node_modules/instagram-private-api/dist/repositories/account.repository.js:149:26)
    at async /home/pi/Tools-for-Instagram/src/login.js:258:31
Login failed from cookie | Removing incorrect cookie | Trying to regenerate...
Incorrect password
Online Mode
(node:7832) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'connect' of undefined
    at login (/home/pi/Tools-for-Instagram/src/login.js:212:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:429:9)
    at async regenerateSession (/home/pi/Tools-for-Instagram/src/regenerateSession.js:13:12)
    at async /home/pi/Tools-for-Instagram/src/login.js:283:20
(node:7832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by quintendewilde** [comment]
Any ideas?!

**Comment by linkfy** [comment]
Can you verify if you get a message on your instagram app? with a message where you need to confirm 'it was me'

**Comment by virginsince1997** [comment]
It's probably your code.
