### ISSUE TITLE
Cannot follow more than two accounts

### ISSUE THREAD

**Issue by DIALLOIMRAN** [linkfy/Tools-for-Instagram#51]
Hi,

When I tried to follow more than two accounts, I got this 

ClientDisconnectedError: MQTToTClient got disconnected.
    at SafeSubscriber._next (/home/idiallo/Desktop/bisol/instabot/node_modules/instagram_mqtt/dist/realtime/realtime.client.js:154:30)
    at SafeSubscriber.__tryOrUnsub (/home/idiallo/Desktop/bisol/instabot/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/idiallo/Desktop/bisol/instabot/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/home/idiallo/Desktop/bisol/instabot/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/home/idiallo/Desktop/bisol/instabot/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Subject.next (/home/idiallo/Desktop/bisol/instabot/node_modules/rxjs/internal/Subject.js:60:25)
    at MQTToTClient.setDisconnected (/home/idiallo/Desktop/bisol/instabot/node_modules/mqtts/dist/mqtt.client.js:330:30)
    at Object.disconnect (/home/idiallo/Desktop/bisol/instabot/node_modules/mqtts/dist/mqtt.client.js:98:26)
    at TLSSocket.<anonymous> (/home/idiallo/Desktop/bisol/instabot/node_modules/mqtts/dist/transport/tls.transport.js:36:52)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on RealtimeClient instance at:
    at RealtimeClient.emitError (/home/idiallo/Desktop/bisol/instabot/node_modules/instagram_mqtt/dist/realtime/realtime.client.js:24:38)
    at SafeSubscriber._next (/home/idiallo/Desktop/bisol/instabot/node_modules/instagram_mqtt/dist/realtime/realtime.client.js:154:20)
    at SafeSubscriber.__tryOrUnsub (/home/idiallo/Desktop/bisol/instabot/node_modules/rxjs/internal/Subscriber.js:205:16)

**Comment by Oyetomi** [comment]
Set ONLINE MODE to false in  .env file

**Comment by DIALLOIMRAN** [comment]
Thanks, @virginsince1997
